// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFeCp8VRHJQzxQvR8r4nWGRYzbP87Rx4Y',
    appId: '1:297033738058:web:9d54a38ac5f9a5834dc3b3',
    messagingSenderId: '297033738058',
    projectId: 'pdify-492b7',
    authDomain: 'pdify-492b7.firebaseapp.com',
    storageBucket: 'pdify-492b7.firebasestorage.app',
    measurementId: 'G-0TFWEB8KR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOb7mfqawPpAi4-5ieFHY9dclPj87iDgg',
    appId: '1:297033738058:android:3063e99bcbb328064dc3b3',
    messagingSenderId: '297033738058',
    projectId: 'pdify-492b7',
    storageBucket: 'pdify-492b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaNtjnXrwQz-4J5zimCoQH6SR-0T2aqGI',
    appId: '1:297033738058:ios:2f120c5126d657354dc3b3',
    messagingSenderId: '297033738058',
    projectId: 'pdify-492b7',
    storageBucket: 'pdify-492b7.firebasestorage.app',
    iosBundleId: 'com.example.pdify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFeCp8VRHJQzxQvR8r4nWGRYzbP87Rx4Y',
    appId: '1:297033738058:web:35dcc7f7cdb020024dc3b3',
    messagingSenderId: '297033738058',
    projectId: 'pdify-492b7',
    authDomain: 'pdify-492b7.firebaseapp.com',
    storageBucket: 'pdify-492b7.firebasestorage.app',
    measurementId: 'G-MQB5PQDHS8',
  );
}
